foreground         #c4c4c5
background         #151318
background_opacity 1.0
cursor             #c4c4c5

active_tab_foreground     #151318
active_tab_background     #c4c4c5
inactive_tab_foreground   #c4c4c5
inactive_tab_background   #151318

active_border_color   #c4c4c5
inactive_border_color #151318
bell_border_color     #69A35A

color0       #151318
color8       #635c70
color1       #69A35A
color9       #69A35A
color2       #F39762
color10      #F39762
color3       #C2C246
color11      #C2C246
color4       #393FA0
color12      #393FA0
color5       #6053A6
color13      #6053A6
color6       #9D68B8
color14      #9D68B8
color7       #c4c4c5
color15      #c4c4c5
