foreground         #c4c7c7
background         #13211f
background_opacity 1.0
cursor             #c4c7c7

active_tab_foreground     #13211f
active_tab_background     #c4c7c7
inactive_tab_foreground   #c4c7c7
inactive_tab_background   #13211f

active_border_color   #c4c7c7
inactive_border_color #13211f
bell_border_color     #ABD167

color0       #13211f
color8       #5e7471
color1       #ABD167
color9       #ABD167
color2       #D7E362
color10      #D7E362
color3       #5B7585
color11      #5B7585
color4       #BB76A2
color12      #BB76A2
color5       #60A0A2
color13      #60A0A2
color6       #64AFB5
color14      #64AFB5
color7       #c4c7c7
color15      #c4c7c7
